name: "Setup envconsul"
description: "Setup the envconsul in a GitHub Actions build environment"
author: "Bloomin' Labs"
inputs:
  envconsul-version:
    description: "Version of the envconsul to install, or 'latest' (default). This accepts semver ranges like ^3.0.0."
    required: true
    default: "latest"
branding:
  icon: "terminal"
  color: "purple"
runs:
  using: "node16"
  main: "dist/index.js"
